### ISSUE TITLE
Update instrcutions with steps to upload prebuild firmware

### ISSUE THREAD

**Issue by lupin-de-mid** [anatoly-savchenkov/lytko-configs#26]
No such instructions right now
I'm unable found http://IP/manual_update without working web interface of factory firmware, but it depends on external server

**Comment by anatoly-savchenkov** [comment]
Enjoy, installation manual (на русском) has arrived (https://github.com/anatoly-savchenkov/lytko-configs/blob/main/docs/installation.rus.md).
