### ISSUE TITLE
Не собирается с  2023.9.3 

### ISSUE THREAD

**Issue by lupin-de-mid** [anatoly-savchenkov/lytko-configs#45]
Cудя по #44  это уже давно
```
INFO ESPHome 2023.9.3
INFO Reading configuration /config/esphome/lytko101hall-6b7b7f.yaml...
INFO Detected timezone 'Europe/Moscow'
INFO Generating C++ source...
INFO Compiling app...
Processing lytko101hall (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 160MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/lytko101hall/src/esphome/components/nextion/nextion.cpp.o
Compiling .pioenvs/lytko101hall/src/esphome/components/nextion/nextion_commands.cpp.o
Compiling .pioenvs/lytko101hall/src/esphome/components/nextion/nextion_upload.cpp.o
Compiling .pioenvs/lytko101hall/src/esphome/components/ntc/ntc.cpp.o
In file included from src/esphome/components/nextion/nextion_commands.cpp:1:
src/esphome/components/nextion/nextion.h:326:29: error: 'esphome::time::ESPTime' has not been declared
  326 |   void set_nextion_rtc_time(time::ESPTime time);
      |                             ^~~~
In file included from src/esphome/components/nextion/nextion_upload.cpp:1:
src/esphome/components/nextion/nextion.h:326:29: error: 'esphome::time::ESPTime' has not been declared
  326 |   void set_nextion_rtc_time(time::ESPTime time);
```
      |                             ^~~~
In file included from src/esphome/components/nextion/nextion.cpp:1:
src/esphome/components/nextion/nextion.h:326:29: error: 'esphome::time::ESPTime' has not been declared
  326 |   void set_nextion_rtc_time(time::ESPTime time);
      |                             ^~~~
src/esphome/components/nextion/nextion_commands.cpp:223:6: error: variable or field 'set_nextion_rtc_time' declared void
  223 | void Nextion::set_nextion_rtc_time(time::ESPTime time) {
      |      ^~~~~~~
src/esphome/components/nextion/nextion_commands.cpp:223:42: error: 'ESPTime' is not a member of 'esphome::time'; did you mean 'esphome::ESPTime'?
  223 | void Nextion::set_nextion_rtc_time(time::ESPTime time) {
      |                                          ^~~~~~~
In file included from src/esphome/components/time/real_time_clock.h:8,
                 from src/esphome/components/nextion/nextion.h:23,
                 from src/esphome/components/nextion/nextion_commands.cpp:1:
src/esphome/core/time.h:12:8: note: 'esphome::ESPTime' declared here
   12 | struct ESPTime {
      |        ^~~~~~~
*** [.pioenvs/lytko101hall/src/esphome/components/nextion/nextion_commands.cpp.o] Error 1
*** [.pioenvs/lytko101hall/src/esphome/components/nextion/nextion_upload.cpp.o] Error 1
*** [.pioenvs/lytko101hall/src/esphome/components/nextion/nextion.cpp.o] Error 1
========================= [FAILED] Took 13.67 seconds =========================

**Comment by anatoly-savchenkov** [comment]
Спасибо за пинок, сейчас снова собирается. Проблема была в коде экрана. Эта прошивка использует немного модифицированный драйвер экрана и он разошелся с основным кодом ESPHome. Проблема исправлена и бинарные прошивки обновлены. Так как в конфигурационном файле используется механизм https://esphome.io/components/external_components.html, то может потребоваться 24 часа для обновления. Или же можно пересобрать, предварительно удалив все файлы (Clean Build Files в HA / ESPHome).

Версии с экраном в моем доме нет, экземпляр термостата для разработки сейчас не доступен. Поэтому проверить версию с экраном на последней версии прошивке не могу. Но проблем не жду, изменения не относятся к функциональности экрана.

**Comment by lupin-de-mid** [comment]
Спасибо, про экран напишу отдельно если что
